### PR TITLE
Update to python3

### PR DESCRIPTION
**Pull request by schneider-f**
Modifications : 
- add () after print fonctions
- matrice multiplication : * to @ since in python 3 * means element-wise multiplication
- replace xrange by range

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on master.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Comment by schneider-f** [comment]
The exampleOLI.py seems to works on my computer : the code runs and the visualization looks physically correct. 
Yet, in the output there are two messages printed several times : < Obj unable to find material ' ' > and < Node "world/OLI" does not exist.>. Were they already printed in the python2 version ? It doesn't seem more problematic than that.

**Comment by nim65s** [comment]
Thanks, but Python 3 is already available on the `topic/python3` branch.

**Comment by schneider-f** [comment]
Hello @nim65s,

I haven't noticed the topic/python3 ! For next users, it may be usefull to add in the main-branch's README  that a python3 version is available.

I have tried the topic/python3 code on my computer and it doesn't seem to work. Should it work ?
Shall I do a PR on the topic/python3 to compare code ?

Thanks for this great package !

**Pull request closed without merging**
